# This is a basic workflow to help you get started with Actions..

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "" > "..\ztmp.txt"
        # run: echo "" > "C:\Users\H616247\Desktop\ztmp.txt"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          & "C:\iar\ewarm-9.60.2\common\bin\iarbuild.exe" "C:\Users\H616247\Desktop\ML99F330Code\ML99F330.ewp" -build Debug
          & "C:\Program Files\SEGGER\JLink_V842\JFlash.exe" -openprj "C:\Users\H616247\Desktop\xz.jflash" -open "C:\Users\H616247\Desktop\ML99F330Code\Debug\Exe\ML99F330.hex" -auto -Exit
          # echo "hello world" >> "..\ztmp.txt"
          # ls >> "..\ztmp.txt"
          # echo "hello world" >> "C:\Users\H616247\Desktop\ztmp.txt"
          # ls >> "C:\Users\H616247\Desktop\ztmp.txt"
         
             

