# This is a basic workflow to help you get started with Actions..

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Process file
        shell: pwsh  # 显式指定PowerShell
        run: |
          # 清空或创建文件（使用绝对路径）
          Set-Content -Path "$env:GITHUB_WORKSPACE/../ztmp.txt" -Value ""
      
          # 追加内容（避免编码问题）
          Add-Content -Path "$env:GITHUB_WORKSPACE/../ztmp.txt" -Value "hello world"
      
          # 列出目录
          Get-ChildItem >> "$env:GITHUB_WORKSPACE/../ztmp.txt"
      
          # 验证结果
          Get-Content "$env:GITHUB_WORKSPACE/../ztmp.txt"
             

